name: Tests
on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
